### ISSUE TITLE
create release on successful build

### ISSUE THREAD

**Issue by ndr-brt** [polymorphicengine/tidal-gui#1]
First of all, great work!
I noticed that's pretty annoying to download the artifact from the action. 
It's possible to make the job releasing and uploading the artifacts so they will be available from the github project "releases" page.

We did it on https://github.com/v7b1/mi-UGens
And it worked pretty well

**Comment by polymorphicengine** [comment]
Ah that's great, thanks for sharing. I was wondering if there was something better, but didn't have time to research yet. I'll have a look at how you did it!

**Comment by ndr-brt** [comment]
I saw that some actions are now deprecated...this seems to be well maintained:
https://github.com/softprops/action-gh-release

**Comment by polymorphicengine** [comment]
Nice! It was super simple! Thanks again!
