### ISSUE TITLE
"GHC Exception: could not execute: bin/fake_gcc.sh" - hardcoded relative path to bin/fake_gcc.sh must be available, which limits symlinking, execution locations

### ISSUE THREAD

**Issue by cleary** [polymorphicengine/tidal-gui#3]
Hi, 
I finally got started with some testing! 

This is looking great, first issue I ran into was trying to symlink the tidal-gui in a PATH dir and while it executes fine, any tidal code evaluations return an error:

```
GHC Exception: could not execute: bin/fake_gcc.sh
```
This seems to be a hardcoded relative link based on the execution dir - it should be able to be executed from anywhere
If I go to any directory other than `binary/` and try to execute, it also fails

**Comment by polymorphicengine** [comment]
ah yes, good catch, you can change the two occurences of `bin/fake_gcc.sh` inside haskell-libs/settings by `$topdir/bin/fake_gcc.sh` and it should work
I'll change the workflows and it should be automatic in the next release
