### ISSUE TITLE
Ambiguous module name

### ISSUE THREAD

**Issue by tonyday567** [polymorphicengine/tidal-gui#9]
On OSX Catalina, it looks like I get a connection with this message, once I satisfy the security stuff:

```
[TidalCycles version 1.7.8]
Installed in /Users/runner/.cabal/store/ghc-8.10.1/tdl-1.7.8-0045ca39/share
Listening for external controls on 127.0.0.1:6010
Connected to SuperDirt.
Listening on http://127.0.0.1:8023
```

But on Ctrl-Return of most any haskell code, I get:

```
Compile error: <no location info>: error:
    Ambiguous module name ‘Sound.Tidal.Transition’:
      it was found in multiple packages: tidal-1.7.8 tidal-1.7.8
```

**Comment by polymorphicengine** [comment]
Hey, thanks for pointing this out.
It seems something went wrong in making the release for mac. 
Just made a new one wich should be done in ~20min, please try that out and see if the problem persists

**Comment by tonyday567** [comment]
And working for me on OSX Catalina (and looking gorgeous!)

Thanks!
